version: '3'

services:
  db:
    build: ./db/.
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  web:
    build: ./app/.
    command: python3 run.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - db